### ISSUE TITLE
Browser freezes while loading feed items

### ISSUE THREAD

**Issue by avbohemen** [david-youster/really-simple-rss#3]
When you click on a feed to load its items, it may take some time to load them (on some feeds 10-15 seconds). In the mean time, the rest of the browser is frozen (for example, I cannot scroll on a page, or change to a different tab) and cpu usage goes to 100% on one core. Is it possible to make the loading of the items async, so the rest of the browser remains responsive?

**Comment by david-youster** [comment]
This should be possible... I'll look into it as soon as I can, and try to get it out in the next version.

**Comment by avbohemen** [comment]
To be a bit more specific, the freeze occurs not necessarily during the loading of the feed, but after the feed is loaded and the feed-items are checked for already visited (I presume, the visited items turn grey instead of black). I guess any optimization/async is needed in this step.

**Comment by david-youster** [comment]
I've just made some changes to the way feed parsing is handled. Would you mind checking if it's helped with your issue at all? The changes are on the master branch, so you can try it out by cloning the repo and loading the add-on via `about:debugging`. Let me know if you see any improvement (or if you don't).

**Comment by avbohemen** [comment]
I just did some testing, and your changes made little difference in the freezing I experience. The delay seems to be in the history search to mark feed items as read (or not). If I comment out lines 85 and 86 in common/feeds.js there is no more delay, and of course, no more marking of read feed items.

To test, I use a pretty slow feed: https://www.anandtech.com/rss/ When it is checking the history, try to change to another tab in firefox. It will delay the tab change until the history is fully checked.

**Comment by avbohemen** [comment]
Ok, I've been playing a bit and the freezing can be completely eliminated, while still marking visited feed items, with a simple change in common/common.css:

From:
```
a {
    text-decoration: none;
    color: black;
}
```
to:
```
a:link {
    text-decoration: none;
    color: black;
}
a:visited {
    text-decoration: none;
    color: #555;
}
```
Oh, and to remove some unnecessary scrollbars, change every instance of "overflow: scroll;" to "overflow: auto;"

The change for common/feeds.js would be:
From:
```
function createAnchor(href, text, title) {
  let maxTooltipLength = 400;
  let anchor = document.createElement('a');
  anchor.href = href;
  anchor.appendChild(document.createTextNode(text));
  if (title != undefined) {
    if (title.length > 512) {
      title = title.substring(0, maxTooltipLength) + '...';
    }
    anchor.title = title;
  }
  browser.history.search({text: href})
    .then((historyItems) => markAsRead(anchor, historyItems));
  return anchor;
}

function markAsRead(anchor, historyItems) {
  if (historyItems.length !== 0) {
    anchor.classList.toggle('old-article');
  } else {
    anchor.onclick = () => anchor.classList.toggle('old-article');
  }
}
```
To:
```
function createAnchor(href, text, title) {
  let maxTooltipLength = 400;
  let anchor = document.createElement('a');
  anchor.href = href;
  anchor.appendChild(document.createTextNode(text));
  if (title != undefined) {
    if (title.length > 512) {
      title = title.substring(0, maxTooltipLength) + '...';
    }
    anchor.title = title;
  }
  return anchor;
}
<EOF>
```

**Comment by david-youster** [comment]
I actually can't reproduce this, but your fix makes sense. Do you want to open a pull request? Alternatively, I can push this change myself (and credit you in the Readme, of course).

**Comment by avbohemen** [comment]
To be honest, I am not all that familiar with github and pull requests. I am not really a coder, I just edit my way around scripts and html whenever I feeld the need. I have created a patch file though, you should be able to use that I think. Other than the above changes, I made a tiny change in the ul and li css to make the list look a little nicer.

The patch file looks like this:

```
diff -u a/common/common.css b/common/common.css
--- a/common/common.css
+++ b/common/common.css
@@ -9,11 +9,14 @@
 }
 
 ul {
-    list-style: none;
+    list-style-type: none;
+    padding: 0;
+    margin: 0;
 }
 
 li {
-    padding-bottom: 5px;
+    padding-left: 8px;
+    padding-bottom: 3px;
     border-bottom: 1px solid #CCC;
 }
 
@@ -21,10 +24,14 @@
     background-color: #EFEFEF;
 }
 
-a {
+a:link {
     text-decoration: none;
     color: black;
 }
+a:visited {
+    text-decoration: none;
+    color: #555;
+}
 
 .feed-title-container {
     display: inline-block;
@@ -49,15 +56,16 @@
 
 #feeds-menu {
     height: 47%;
-    overflow: scroll;
+    overflow: auto;
     border-bottom: none;
 }
 
 #controls {
     height:7%;
     padding-left: 1em;
-    overflow:scroll;
+    overflow: auto;
     text-align: center;
+    border: 1px solid #AAA;
 }
 
 #controls input {
@@ -67,9 +75,5 @@
 #display {
     border: none;
     height: 50%;
-    overflow: scroll;
-}
-
-.old-article {
-    color: #555;
+    overflow: auto;
 }
diff -u a/common/feeds.js b/common/feeds.js
--- a/common/feeds.js
+++ b/common/feeds.js
@@ -82,15 +82,5 @@
     }
     anchor.title = title;
   }
-  browser.history.search({text: href})
-    .then((historyItems) => markAsRead(anchor, historyItems));
   return anchor;
-}
-
-function markAsRead(anchor, historyItems) {
-  if (historyItems.length !== 0) {
-    anchor.classList.add('old-article');
-  } else {
-    anchor.onclick = () => anchor.classList.add('old-article');
-  }
 }
```

**Comment by david-youster** [comment]
Thanks for taking the time - I've applied this change against the code already, I'll release it as soon as I have a chance.
