### ISSUE TITLE
Feature Request: dark mode

### ISSUE THREAD

**Issue by SpineEyE** [david-youster/really-simple-rss#5]
A dark mode would be nice, probably just a matter of black background, white font and inverted icons.

Would be nice if the extension could recognize whether Firefox uses a dark theme at the moment.

These links should help:

https://discourse.mozilla.org/t/detecting-theme-color-current-results-return-transparent/2608/2

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme/getCurrent

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme/onUpdated

**Comment by david-youster** [comment]
Working on this at the moment (but without the dark theme detection, I'm afraid). Not sure when it'll be ready, but watch this space!
