### ISSUE TITLE
Feed for dpreview.com does not parse

### ISSUE THREAD

**Issue by avbohemen** [david-youster/really-simple-rss#6]
The feeds for the site https://dpreview.com are discovered, but they are not parsed properly. For example, this one: https://www.dpreview.com/feeds/reviews.xml (the discovered feed is http, not https, but both do not parse).

**Comment by david-youster** [comment]
Thanks for reporting this - I've pushed a fix for this to the master branch, I'll release it as soon as possible.

**Comment by david-youster** [comment]
The fix for this has been released. Going to close this.
